import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { remarkMermaid } from './plugins/remark-mermaid.mjs';

// Project GitHub Pages site: https://calvinchengx.github.io/azure-keyvault-emulator/
//
// The docs are published one level down, under /docs/, because the site root
// is the hand-written landing page in site/index.html. The workflow assembles
// `_site/index.html` + `_site/docs/` from the two halves, so this base and
// that layout have to be changed together: a base of `/azure-keyvault-emulator/`
// with the docs served from /docs/ resolves every internal link and asset one
// directory too high, and Starlight would still build cleanly.
export default defineConfig({
  site: 'https://calvinchengx.github.io',
  base: '/azure-keyvault-emulator/docs/',
  // remarkMermaid turns ```mermaid fences into <pre class="mermaid"> before
  // Expressive Code sees them; src/components/Head.astro renders them client-side.
  markdown: {
    remarkPlugins: [remarkMermaid],
  },
  integrations: [
    starlight({
      title: 'Azure Key Vault Emulator',
      components: {
        Head: './src/components/Head.astro',
        // Top nav: the parity version picker, rendered beside the search box.
        Search: './src/components/Search.astro',
      },
      description:
        'A local emulator of the Azure Key Vault data plane — secrets, keys, and certificates — with real challenge-based authentication against entra-emulator.',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/calvinchengx/azure-keyvault-emulator' },
      ],
      editLink: {
        baseUrl: 'https://github.com/calvinchengx/azure-keyvault-emulator/edit/main/docs/',
      },
      sidebar: [
        {
          label: 'Getting started',
          items: [
            { slug: 'index' },
            { slug: '01-quickstart' },
            { slug: '02-installation' },
            { slug: '14-platform-setup' },
            { slug: '03-architecture' },
            { slug: '04-configuration' },
            { slug: '05-tls-and-vaults' },
          ],
        },
        {
          label: 'Reference',
          items: [
            { slug: '06-secrets' },
            { slug: '07-keys' },
            { slug: '08-certificates' },
            { slug: '09-authentication' },
          ],
        },
        {
          label: 'Testing',
          items: [
            { slug: '10-testing' },
            { slug: '11-family-integration' },
          ],
        },
        {
          label: 'Project',
          items: [
            { slug: '12-roadmap' },
            { slug: '13-entra-companion' },
          ],
        },
        {
          // The live map first, then the pages generated by
          // scripts/parity-versions.mjs from the git release tags. The history
          // index lists every per-version snapshot, so it doubles as the version
          // browser (this Starlight's sidebar has no autogenerate). The map's own
          // title is long; in this group it just needs to say Parity.
          label: 'Parity',
          items: [
            { slug: 'parity', label: 'Parity' },
            { slug: 'parity-history' },
            { slug: 'parity-history/changelog' },
          ],
        },
      ],
    }),
  ],
});
